# Generated by Django 6.0.6 on 2026-07-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depadrments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depadrments_db',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
