# Generated by Django 6.0.6 on 2026-07-02 20:31

import voiteID.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID_DB',
            fields=[
                ('_c_id', models.CharField(default=voiteID.models.generate_voting_id, editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('_is_used', models.BooleanField(default=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ID_',
                'verbose_name_plural': 'IDYADA',
                'ordering': ['_c_id'],
            },
        ),
    ]
