# Generated by Django 6.0.6 on 2026-07-02 20:31

import Musharax.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Depadrments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='musharax_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(help_text='Enter candidate name.', max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[A-Za-zÀ-ÿ\\s]+$')])),
                ('m_email', models.EmailField(help_text='Enter candidate email.', max_length=254, unique=True)),
                ('m_joined', models.DateTimeField(auto_now_add=True)),
                ('m_image', models.ImageField(upload_to='musharax_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), Musharax.models.validate_image_size, Musharax.models.validate_image_content])),
                ('m_depadrments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depadrments.depadrments_db')),
            ],
            options={
                'verbose_name': 'Musharax',
                'verbose_name_plural': 'Musharaxiin',
            },
        ),
    ]
