# Generated by Django 6.0.6 on 2026-07-03 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musharax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musharax_db',
            name='m_gender',
            field=models.CharField(choices=[('lab', 'Lab'), ('dhadig', 'DHadig')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='musharax_db',
            name='m_username',
            field=models.CharField(blank=True, help_text='Gali musharax username.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='musharax_db',
            name='m_email',
            field=models.EmailField(help_text='gali emailka musharaxa.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='musharax_db',
            name='m_name',
            field=models.CharField(help_text='gali magaca musharaxa.', max_length=100, validators=[django.core.validators.RegexValidator(message='gali magac saxa ah isticmal xarfo.', regex='^[A-Za-zÀ-ÿ\\s]+$')]),
        ),
    ]
