# Generated by Django 6.0.6 on 2026-07-11 11:08

import Musharax.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musharax', '0002_musharax_db_m_gender_musharax_db_m_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musharax_db',
            name='m_if_allowed',
            field=models.BooleanField(default=False, help_text='Ma  Tartami Kara musharaxa.'),
        ),
        migrations.AlterField(
            model_name='musharax_db',
            name='m_image',
            field=models.ImageField(upload_to='static/musharax_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), Musharax.models.validate_image_size, Musharax.models.validate_image_content]),
        ),
    ]
