# Generated by Django 6.0.6 on 2026-07-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musharax', '0003_musharax_db_m_if_allowed_alter_musharax_db_m_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musharax_db',
            name='m_image',
            field=models.URLField(blank=True, help_text='Supabase Public URL for the candidate image.', max_length=500, null=True),
        ),
    ]
