# Generated by Django 6.0.6 on 2026-07-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Depadrments', '0001_initial'),
        ('Musharax', '0001_initial'),
        ('voiteID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codbixiye_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='Depadrments.depadrments_db')),
                ('c_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codbixiye', to='voiteID.id_db')),
                ('c_musharax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codbixiye', to='Musharax.musharax_db')),
            ],
            options={
                'verbose_name': 'Codbixiye',
                'verbose_name_plural': 'Codbixiyeyaal',
                'ordering': ['c_id'],
            },
        ),
    ]
