# Generated by Django 6.0.6 on 2026-07-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codbixiye', '0001_initial'),
        ('voiteID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codbixiye_db',
            name='c_gender',
            field=models.CharField(choices=[('lab', 'Lab'), ('dhadig', 'DHadig')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='codbixiye_db',
            name='c_id',
            field=models.OneToOneField(limit_choices_to={'_is_used': False}, on_delete=django.db.models.deletion.CASCADE, related_name='codbixiye', to='voiteID.id_db'),
        ),
    ]
